CREATE DATABASE IF NOT EXISTS mydatabase;
USE mydatabase;


CREATE TABLE DEPT (
    DEPTNO INT,
    DNAME VARCHAR(20),
    LOC VARCHAR(20)
);

SELECT * FROM DEPT;
RENAME TABLE DEPT TO DEPARTMENT;


ALTER TABLE DEPARTMENT
ADD COLUMN PINCODE INT NOT NULL;

ALTER TABLE DEPARTMENT
DROP COLUMN PINCODE;
 

ALTER TABLE DEPARTMENT
CHANGE COLUMN DNAME DEPT_NAME VARCHAR(20);


ALTER TABLE DEPARTMENT
MODIFY COLUMN LOC CHAR(10);

DROP TABLE DEPARTMENT;